CREATE TABLE IF NOT EXISTS tweet (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	message_id INTEGER NOT NULL DEFAULT 0 UNIQUE KEY,
	author_id VARCHAR(20) NOT NULL,
	tweet_message VARCHAR(1000),
	timestamp TIMESTAMP NOT NULL
);