CREATE DATABASE IF NOT EXISTS log;
USE log;

CREATE TABLE IF NOT EXISTS url_call_log (
	id INTEGER UNIQUE KEY AUTO_INCREMENT,
	ip VARCHAR(20),
	api VARCHAR(100),
	url VARCHAR(100),
	data VARCHAR(1000),
	timestamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS app_log (
	id INTEGER UNIQUE KEY AUTO_INCREMENT,
	app_id VARCHAR(20), -- universal id
	log VARCHAR(1000),
	timestamp TIMESTAMP NOT NULL
);