#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

START=50

start() {
	mkdir -m 0755 -p /opt/var/log/lighttpd
	service_start /opt/usr/sbin/lighttpd -f /opt/etc/lighttpd/lighttpd.conf
}

stop() {
	service_stop /opt/usr/sbin/lighttpd
}

